---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=./roles' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook playbook.yml -i inventory --syntax-check

  # Run the playbook
  - ansible-playbook playbook.yml -i inventory

  # Run the role/playbook again, checking to make sure it's idempotent.
  - >
    ansible-playbook -i inventory playbook.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

  # Run functional tests?
